# Site settings
title: "Munmun + Manjeet"
description: |
    Munsyari, Uttarakhand

    May 04, 2018
owner: Manjeet
first_published: 2017
email: mark@mark.gg
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.munmunandmanjeet.wedding" # the base hostname & protocol for your site

social:
  github: https://github.com/man74pangtey

# Build settings
markdown: kramdown
